### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by ktf**
* Move to latest version of ImGUI.
* Expose HandMadeMath.h and gl3w.h for those who want to use it.

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr can you check if this simplifies your life?

**Comment by davidrohr** [comment]
@ktf : sorry, I was stupid and missed this.PR .. too many github mails
Could you compare to #16 
I think it is better to install the GL headers in the GL/... folder, like it is usually done with GL headers.
Also, I have added the KHB header, which is by default included by the gl3w header. I think you manually changed the variable types to not use the khb stuff? Or why didn't your gl3w header not use khrplatform.h.
Anyhow, also this should work for me, would just need to adapt the include paths, and use different include paths depending on whether I build on O2 or standalone.

**Comment by davidrohr** [comment]
@ktf : I think we need parts of both, this PR and #16, to have new ImGUI and new gl3w.
How about you merge this one, then I'll rebase #16 onto master?

**Comment by ktf** [comment]
Sorry I forgot about this.

**Pull request merged**
